dist: xenial
sudo: false
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc

install:
  - pip install coveralls -r requirements.txt

script:
  - flake8
  - coverage run --source yandex_geocoder -m pytest

after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PyPiLogin
  password: $PyPiPassword
  on:
    tags: true
    python: "3.7"
