language: python
cache: pip

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc

install:
  - pip install coveralls tox-travis -r requirements.txt

script:
  - flake8
  - tox

after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PyPiLogin
  password: $PyPiPassword
  on:
    tags: true
